name: null
favicon: null
layout_spectrum: 0.22127
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: 'http://www.budweiser.com/'
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2067a9'
    - '#030406'
    - '#332b1e'
    - '#053063'
    - '#938b7e'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose:
  - name: follow
    item: eb0d364a-2499-4f5e-a6e4-dd4dd1614839
    url: 'http://www.budweiser.com/'
