name: null
favicon: null
layout_spectrum: 0.45855
typography_spectrum: 0.5094
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e1c21'
    - '#c9e5fd'
    - '#aa1e43'
    - '#aa959a'
    - '#00a3cc'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose:
  - name: follow
    item: null
    url: null
