name: null
favicon: null
layout_spectrum: 0.14499
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0e1213'
    - '#94362a'
    - '#b2b3b7'
    - '#688a34'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose:
  - name: follow
    item: eb0d364a-2499-4f5e-a6e4-dd4dd1614839
    url: null
