name: null
favicon: null
layout_spectrum: 0.86533
typography_spectrum: 0.80601
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0e1213'
    - '#94362a'
    - '#b2b3b7'
    - '#688a34'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
purpose:
  - name: follow
    item: ef025f0d-d3d5-4446-9632-b0e9124f5849
    url: null
